# Generated by Django 5.0.3 on 2024-03-30 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={'verbose_name': 'Reaction', 'verbose_name_plural': 'Reactions'},
        ),
    ]
