# Generated by Django 5.0.3 on 2024-03-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_reaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reaction',
            field=models.ManyToManyField(related_name='posts', to='blog.reaction', verbose_name='Reaction'),
        ),
    ]
