# Generated by Django 5.0.3 on 2024-03-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_reaction_delete_reaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('👍', '👍'), ('👎', '👍'), ('❤️', '❤️'), ('😲', '😲'), ('😢', '😢'), ('🤣', '🤣'), ('😡', '😡'), ('❤️\u200d🩹', '❤️\u200d🩹'), ('❤️', '❤️')], max_length=10)),
            ],
        ),
    ]
