# Generated by Django 5.0.3 on 2024-03-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_reaction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reaction',
            field=models.ManyToManyField(related_name='posts', to='blog.reaction', verbose_name='Reaction'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='type',
            field=models.CharField(choices=[('👍', '👍'), ('👎', '👎'), ('❤️', '❤️'), ('😲', '😲'), ('😢', '😢'), ('🤣', '🤣'), ('😡', '😡'), ('❤️\u200d🩹', '❤️\u200d🩹'), ('🤗', '🤗')], max_length=10),
        ),
    ]
