# Generated by Django 5.0.3 on 2024-03-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_reaction_name_reaction_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='name',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
