# Generated by Django 5.0.3 on 2024-03-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_reaction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
