# Generated by Django 5.0.3 on 2024-04-10 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_rename_category_categorys_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.tag'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='post',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
