# Generated by Django 5.0.3 on 2024-04-10 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_visit_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.tag'),
        ),
    ]
