# Generated by Django 5.0.3 on 2024-04-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_visit_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='tag',
        ),
    ]
