# Generated by Django 5.0.3 on 2024-03-31 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('👍', '👍'), ('👎', '👎'), ('❤️', '❤️'), ('😲', '😲'), ('😢', '😢'), ('🤣', '🤣'), ('😡', '😡'), ('❤️\u200d🩹', '❤️\u200d🩹'), ('🤗', '🤗')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='comment.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='reaction',
            field=models.ManyToManyField(related_name='posts', to='comment.reaction', verbose_name='Reaction'),
        ),
    ]
