# Generated by Django 5.0.3 on 2024-03-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_reaction_reply_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reaction',
            field=models.ManyToManyField(related_name='comment_reactions', to='comment.reaction', verbose_name='Reaction'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reaction',
            field=models.ManyToManyField(related_name='reply_reactions', to='comment.reaction', verbose_name='Reaction'),
        ),
    ]
