# Generated by Django 5.0.3 on 2024-03-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment_reaction_alter_reply_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reaction',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reaction',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
