# Generated by Django 5.0.3 on 2024-03-31 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_reactiontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='object_id',
        ),
    ]
