# Generated by Django 5.0.3 on 2024-03-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_reaction_comment_reaction_post_reaction_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reaction_type',
            field=models.CharField(default=1, max_length=10, unique=False),
        ),
    ]
