# Generated by Django 5.0.3 on 2024-03-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0011_remove_comment_reaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reactions',
            field=models.CharField(default=1, max_length=10, unique=False),
        ),
    ]
