# Generated by Django 5.0.3 on 2024-03-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0012_comment_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reactions',
            field=models.CharField(default='a', max_length=10, unique=False),
        ),
    ]
