# Generated by Django 5.0.3 on 2024-03-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0014_alter_comment_reactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reactions',
        ),
        migrations.AddField(
            model_name='comment',
            name='reaction_type',
            field=models.CharField(default=2, max_length=100),
        ),
    ]
