# Generated by Django 5.0.3 on 2024-03-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0015_remove_comment_reactions_comment_reaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reaction_type',
            field=models.CharField(max_length=100),
        ),
    ]
