# Generated by Django 5.0.3 on 2024-04-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0016_alter_comment_reaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='reaction_type',
        ),
        migrations.AddField(
            model_name='reaction',
            name='reaction_types',
            field=models.ManyToManyField(related_name='comments', to='comment.reactiontype'),
        ),
    ]
