# Generated by Django 5.0.3 on 2024-04-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0020_alter_reaction_reaction_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReactionType',
        ),
    ]
