# Generated by Django 5.0.3 on 2024-04-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0021_delete_reactiontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reaction_type',
        ),
    ]
