# Generated by Django 5.0.3 on 2024-04-04 22:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0024_comment_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.ManyToManyField(related_name='reply_likes', to=settings.AUTH_USER_MODEL, verbose_name='reply_likes'),
        ),
    ]
