# Generated by Django 5.0.3 on 2024-04-08 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0025_reply_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='AnonymousLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.reply')),
            ],
        ),
    ]
